### ISSUE TITLE
Класс выбранного элемента

### ISSUE THREAD

**Issue by xcopy** [coderiver/tvoeresume#1]
Надо добавить css класс для выбранного/активного элемента.

Например, в слайде с годами поступления какой-нибудь год надо отментить как активный/выбранный.

Что-то вроде:

``` html
<span class="selected">2011</span>
```

И так для всех последующих слайдов.

**Comment by 2bj** [comment]
Класс есть, но не работает пока

![Alt text](https://monosnap.com/file/FMbsjGLcj5KP8yGDxjTVKNCL5qprR7.png)

**Comment by etna-scorpio** [comment]
исправили в последнем коммите

**Comment by xcopy** [comment]
Во всех слайдах будет использоваться `is-active` ?

PS. Может просто `active`, а то `is-active` звучит как вопрос (ну или флаг)

**Comment by etna-scorpio** [comment]
да, во всех, где на макете явно обозначен активный элемент. без проблем, можно переименовать и в active

**Comment by xcopy** [comment]
Круто, спасибо
