### ISSUE TITLE
Курсы

### ISSUE THREAD

**Issue by xcopy** [coderiver/tvoeresume#12]
@2bj, нужен ли разделитель между формами?

![_ _-_2015-06-29_10 58 13](https://cloud.githubusercontent.com/assets/202339/8401265/fc66d510-1e4d-11e5-8ce3-bf2d2e59e4c1.png)

**А также должна быть возможность удалить добавленную строку (на случай если row будет лишним или случайным)**

**Comment by 2bj** [comment]
да

**Comment by xcopy** [comment]
@etna-scorpio, сделаете?

**Comment by 2bj** [comment]
Погоди, ща дизайн найдем (или нарисуем)

**Comment by 2bj** [comment]
Дизайн рисуется.

**Comment by xcopy** [comment]
@2bj, что-нибудь известно о судьбе дизайна?

**Comment by xcopy** [comment]
btw:

> А также должна быть возможность удалить добавленную строку (на случай если row будет лишним или случайным)

**Comment by 2bj** [comment]
да

**Comment by xcopy** [comment]
Вот, что происходит по умолчанию (только одна строка)

![_ _-_2015-07-06_11 03 30](https://cloud.githubusercontent.com/assets/202339/8515972/d80d6496-23ce-11e5-913b-13a7b5a47cf1.png)
