### ISSUE TITLE
Error tooltips

### ISSUE THREAD

**Issue by xcopy** [coderiver/tvoeresume#13]
Ребята, смотрите что у меня получается (вернее, не получается)
- Обратите внимание на ошибку между именем и телефоном
  ![screenshot from 2015-06-30 10 52 10](https://cloud.githubusercontent.com/assets/202339/8424151/bb49a11e-1f17-11e5-8841-d27c2cada041.png)
- Ошибка между датой "С" и датой "ПО" (т.е. ошибка относится к дате "С"). А также ошиба для textarea съезжает
  ![screenshot from 2015-06-30 10 54 45](https://cloud.githubusercontent.com/assets/202339/8424166/0f1a8f7e-1f18-11e5-8795-588be2b22421.png)
- Ошибка для УРЛа осталась под батоном
  ![screenshot from 2015-06-30 10 57 07](https://cloud.githubusercontent.com/assets/202339/8424187/6341ade4-1f18-11e5-8f15-89c6263cdac1.png)
- Тут, думаю, все понятно в чем дело
  ![screenshot from 2015-06-30 10 58 59](https://cloud.githubusercontent.com/assets/202339/8424201/959d8556-1f18-11e5-8d32-49d8516ea0f5.png)
- И еще, вот: текст внутри тултипа может быть разного размера.

![screenshot from 2015-06-30 12 28 20](https://cloud.githubusercontent.com/assets/202339/8425050/aed3f0a4-1f23-11e5-88f6-193c2500500c.png)

![screenshot from 2015-06-30 12 31 01](https://cloud.githubusercontent.com/assets/202339/8425066/f5559f82-1f23-11e5-9511-7f9241706234.png)

ЗЫ. В общем, было бы неплохо сделать тултипы для всех элементов формы, где они встречаются.

@2bj, есть что добавить?

**Comment by 2bj** [comment]
Да, за основу взять готовое решение и немного подогнать UI.

**Comment by xcopy** [comment]
@2bj, да что-то вроде [Bootstrap tooltips](http://getbootstrap.com/javascript/#tooltips)

**Comment by 2bj** [comment]
UI необязательно точ-в-точ подгонять, достаточно будет только по цветам.

**Comment by xcopy** [comment]
Как на счет второго скриншота? Тултип для textarea. Ориентиры: charge.html, traits.html, hobby.html

**Comment by xcopy** [comment]
Еще очень важно, чтобы `<i class="icon-error"></i>` шёл сразу после элемента формы.
