### ISSUE TITLE
Расположение индикатора

### ISSUE THREAD

**Issue by xcopy** [coderiver/tvoeresume#3]
Блок с индикатором (это какбэ общий блок) надо бы вынести за пределы шаблона, т.е. в лейаут/скелетон. Сейчас он инклудится в каждую вьюху, чего нам не надо.

**Comment by etna-scorpio** [comment]
что именно за индикатор? можно класс или скрин блока?

**Comment by xcopy** [comment]
``` jade
include slide-nav
```

ну, круглежки которые

**Comment by etna-scorpio** [comment]
вроде как относится к слайду, который является контентной частью?

**Comment by xcopy** [comment]
Хм, к слайду точно относятся "Назад" и "Вперед", а индикатор должен быть частью скелета.

**Comment by etna-scorpio** [comment]
окей, перенесем
