### ISSUE TITLE
Исправления от клиента

### ISSUE THREAD

**Issue by akella** [coderiver/tvoeresume#5]
1. Слайд: skills.html

Стрелка вниз скроллит верхний блок выбора навыков, так как там их может быть больше, чем в дизайне. При скролле вниз добавить стрелку вверх, которая скроллит в обратную сторону. 

Этот комментарий ко всем слайдам, где есть подобные блоки, а именно к:
- слайд: career-specialty.html
- слайду "Твой опыт работы или практики (кем ты работал)" - не знаю названия этого слайда в псд формате
1. Слайд: skills.html

Нижний блок "Что ты знаешь и умеешь делать" следует сделать редактируемым, с возможностью дописывать текст самим (а-ля free tag selector) - относится только к этому слайду.

например, как здесь: http://xoxco.com/projects/code/tagsinput/example.html
1. Слайд: career.html

Значки в иконках нужно сделать фиксированными вне зависимости от текста. Они должны вставляться как tag img  (или style" background-image), потому что мы их загружаем через админку.
Максимальное количество строк - 2 строки
Всегда выравниваем текст по центру, как горизонтально, так и вертикально

**Comment by akella** [comment]
Давайте сделаем https://select2.github.io/examples.html такие селекты

**Comment by 2bj** [comment]
и в free tag selector тоже заюзать select2

**Comment by etna-scorpio** [comment]
первый пункт сделан

**Comment by etna-scorpio** [comment]
второй пункт тоже
