### ISSUE TITLE
cursor: pointer

### ISSUE THREAD

**Issue by xcopy** [coderiver/tvoeresume#6]
Курсор для элементов индикатора (`<ul class="slide-nav-indication">..</ul>`) надо сделать пойнтером

**Comment by etna-scorpio** [comment]
так это ссылки? или просто индикатор состояния?

**Comment by xcopy** [comment]
Да, лучше сделать ссылками

2015-06-17 19:25 GMT+06:00 Etna notifications@github.com:

> так это ссылки? или просто индикатор состояния?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/coderiver/tvoeresume/issues/6#issuecomment-112798736.

## 

Best regards, Kairat Jenishev
