### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by xcopy** [coderiver/tvoeresume#7]
Остались два слайда

**4. Укажи желаемый доход**
![4](https://cloud.githubusercontent.com/assets/202339/8279406/238a0156-18f6-11e5-8f20-00e4ba35ef3a.jpg)

**5.2. Выбери режим работы (тип занятости)**
![2 6_2](https://cloud.githubusercontent.com/assets/202339/8279410/353cfe26-18f6-11e5-89d9-928697426932.png)

**Comment by etna-scorpio** [comment]
заканчиваем Проверку резюме учителем и приступаем к оставшимся
